# Ticker
DEFAULT_TICKER = "SPY"

# Date range
START_DATE = "2000-01-01"

# Model parameters
N_COMPONENTS = 4
RANDOM_STATE = 42
COVARIANCE_TYPE = "full"
N_INIT = 50

# Feature engineering
ROLLING_WINDOW = 20
MOMENTUM_WINDOW = 20